### ISSUE TITLE
Game crashes when trying to access Freeroam status

### ISSUE THREAD

**Issue by IDeletedSystem64** [Tarasa24/SCS_RPC2#1]
The game seems to always crash when loading the free roam status, tested on a fresh save. 
[game.crash.txt](https://github.com/Tarasa24/SCS_RPC2/files/5478833/game.crash.txt)
[game.log.txt](https://github.com/Tarasa24/SCS_RPC2/files/5478834/game.log.txt)
Crashes with C0000005 ACCESS_VIOLATION

**Comment by Tarasa24** [comment]
Hi, thanks for the issue. Looks like my code is trying to access memory that has been since allocated by another plugin. Can you please provide a list of plugins you run alongside SCS_RP2, so I can see if I can recreate the problem.

**Comment by IDeletedSystem64** [comment]
I had ets2telemetry and Trucksbook installed though I'm going to try it without them

**Comment by IDeletedSystem64** [comment]
Even after removing the plugins it's still crashing with ACCESS_VIOLATION

[game.crash.txt](https://github.com/Tarasa24/SCS_RPC2/files/5482170/game.crash.txt)
[game.log.txt](https://github.com/Tarasa24/SCS_RPC2/files/5482171/game.log.txt)

**Comment by Tarasa24** [comment]
Verify that you have all of these updated. Although they should be, since you are running other plugins without a problem.

- [.NET Framework](https://www.microsoft.com/en-us/download/details.aspx?id=55170)
- [DirectX](https://www.microsoft.com/en-us/download/details.aspx?id=35)
- [Microsoft Visual C++](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

Would it be a possibility for you to compile the dlls yourself. Perhaps there is an issue with the binary itself.

**Comment by IDeletedSystem64** [comment]
They're all up to date, Tried compiling in VS and running it with the same issue. though it runs fine with the Paused and Close to statuses

**Comment by Tarasa24** [comment]
I tried patching up some for loops and couple of other things. As I am unable to replicate the behavior on my machine, I need you to test this binary [SCS_RPC2.zip](https://github.com/Tarasa24/SCS_RPC2/files/5483142/SCS_RPC2.zip)

**Comment by IDeletedSystem64** [comment]
Continues to crash at the freeroam status with the new version 
[game.crash.txt](https://github.com/Tarasa24/SCS_RPC2/files/5483748/game.crash.txt)
[game.log.txt](https://github.com/Tarasa24/SCS_RPC2/files/5483750/game.log.txt)

**Comment by Tarasa24** [comment]
As mentioned I can't replicate said behavior, so I sadly can't really help no further. If you or anybody else who might have same issue, feel like digging into the code I have multiple observations:

- The issue is that the program tries to read from memory that is inaccessible to it (known as segmentation fault).
- Thanks to changes in 3907783437a6e4ea4ce3089a2989551ec7b266f8 the *game.crash.txt* got shortened of one block. I think it might've fixed something.
- Per description of the problem I guess the issue might be somewhere in the `handle_configuration` function, because the event it handles fires first when player loads into the world (*the point of crash?*).
https://github.com/Tarasa24/SCS_RPC2/blob/3907783437a6e4ea4ce3089a2989551ec7b266f8/handlers.h#L83-L121

**Comment by IDeletedSystem64** [comment]
Closed as the issue seems to be with the tutorial part of the game as when trying it on my normal profile it runs fine on the first release

**Comment by Tarasa24** [comment]
Now fixed in the release [1.1](https://github.com/Tarasa24/SCS_RPC2/releases/tag/1.1). 
Turned out that after the tutorial, for some reason, the speed channel fires with a null pointer `value` , that caused the crash.

Thank you for the report
